export interface EPerson {
    givenName: string;
    surname: string;
    age: string;
    email: string;
    education: string;
}

export const ManyPerson: EPerson[] = [
    {
      givenName: 'Sarah',
      surname: 'Howard',
      age: '41',
      email: 's.m.howard@yahoo.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Alexander',
      surname: 'Turner',
      age: '43',
      email: 'alexanderfturner@gmail.com',
      education: 'Master’s degree',
    },
    {
      givenName: 'Brianna',
      surname: 'Russell',
      age: '32',
      email: 'b_g_russell@yahoo.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Ashley',
      surname: 'Ward',
      age: '64',
      email: 'amward@rocketmail.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Alexandra',
      surname: 'Campbell',
      age: '76',
      email: 'alexandracampbell@hotmail.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Jonathan',
      surname: 'Scott',
      age: '26',
      email: 'jonathanscott@ymail.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Tyler',
      surname: 'Moore',
      age: '62',
      email: 'tyler_j_moore@live.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Laura',
      surname: 'Johnson',
      age: '58',
      email: 'lrjohnson29@rocketmail.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Melissa',
      surname: 'Garcia',
      age: '33',
      email: 'mlgarcia77@gmail.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Ethan',
      surname: 'Hill',
      age: '67',
      email: 'e_m_hill@yahoo.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Samuel',
      surname: 'Baker',
      age: '51',
      email: 's_baker@ymail.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Charles',
      surname: 'Powell',
      age: '53',
      email: 'charles.powell@gmail.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Jeremy',
      surname: 'Brown',
      age: '62',
      email: 'j.brown53@aol.com',
      education: 'Master’s degree',
    },
    {
      givenName: 'Haley',
      surname: 'White',
      age: '70',
      email: 'haley.m.white26@hotmail.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Austin',
      surname: 'Hayes',
      age: '58',
      email: 'austin.hayes@gmail.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Jennifer',
      surname: 'Thomas',
      age: '40',
      email: 'jenniferthomas@aol.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Emily',
      surname: 'Scott',
      age: '68',
      email: 'emily.kay.scott@yahoo.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Charles',
      surname: 'Allen',
      age: '43',
      email: 'c_e18@ymail.com',
      education: 'Master’s degree',
    },
    {
      givenName: 'Heather',
      surname: 'Jenkins',
      age: '65',
      email: 'h.l@gmail.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Richard',
      surname: 'Flores',
      age: '51',
      email: 'r.flores@outlook.com',
      education: 'Master’s degree',
    },
    {
      givenName: 'Charlotte',
      surname: 'Perry',
      age: '62',
      email: 'c.i.perry@ymail.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Tiffany',
      surname: 'Miller',
      age: '59',
      email: 'tiffany_s_miller@rocketmail.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Emily',
      surname: 'Torres',
      age: '45',
      email: 'emily_torres@gmail.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Allison',
      surname: 'Thomas',
      age: '75',
      email: 'allison.m.thomas@gmail.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Katherine',
      surname: 'Brooks',
      age: '76',
      email: 'katherine.a93@gmail.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Hannah',
      surname: 'Robinson',
      age: '32',
      email: 'hannahrrobinson@live.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Amber',
      surname: 'Wright',
      age: '60',
      email: 'a.g.wright@hotmail.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Sophia',
      surname: 'Bell',
      age: '53',
      email: 's_bell11@live.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Eleanor',
      surname: 'Long',
      age: '58',
      email: 'eleanorllong31@gmail.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Adam',
      surname: 'Jones',
      age: '42',
      email: 'adam_a_jones@outlook.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Eric',
      surname: 'Lee',
      age: '73',
      email: 'e.lee@gmail.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Jack',
      surname: 'Young',
      age: '76',
      email: 'j.r.young@rocketmail.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Ryan',
      surname: 'Lewis',
      age: '70',
      email: 'ryan@yahoo.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Joshua',
      surname: 'Campbell',
      age: '66',
      email: 'ja74@outlook.com',
      education: 'Master’s degree',
    },
    {
      givenName: 'John',
      surname: 'Sanders',
      age: '58',
      email: 'j_sanders@aol.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Eleanor',
      surname: 'Long',
      age: '71',
      email: 'eleanorlong@rocketmail.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Ryan',
      surname: 'Clark',
      age: '38',
      email: 'r.clark14@live.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Grace',
      surname: 'Martinez',
      age: '25',
      email: 'gmartinez@hotmail.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Joshua',
      surname: 'Gonzales',
      age: '72',
      email: 'joshuaa89@hotmail.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Aaron',
      surname: 'Peterson',
      age: '32',
      email: 'arpeterson32@aol.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Joseph',
      surname: 'Baker',
      age: '35',
      email: 'joseph.r.baker@hotmail.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Sean',
      surname: 'Ramirez',
      age: '42',
      email: 'sean.ramirez9@aol.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Eric',
      surname: 'Griffin',
      age: '21',
      email: 'egriffin66@hotmail.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Kyle',
      surname: 'Bell',
      age: '18',
      email: 'kylebell@live.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Aubrey',
      surname: 'Bailey',
      age: '34',
      email: 'aubreyjbailey@outlook.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Sarah',
      surname: 'Flores',
      age: '48',
      email: 's.d.flores@yahoo.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Alexis',
      surname: 'Bennett',
      age: '65',
      email: 'alexis.rose.bennett60@hotmail.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Amber',
      surname: 'Rivera',
      age: '45',
      email: 'arivera@yahoo.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Aubrey',
      surname: 'Jackson',
      age: '69',
      email: 'a.i.jackson@ymail.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Henry',
      surname: 'Harris',
      age: '19',
      email: 'hharris@yahoo.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Julian',
      surname: 'Wilson',
      age: '35',
      email: 'j_wilson69@gmail.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Charlotte',
      surname: 'Washington',
      age: '29',
      email: 'c.washington45@rocketmail.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Daniel',
      surname: 'Collins',
      age: '69',
      email: 'daniel.collins@outlook.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Michael',
      surname: 'Simmons',
      age: '29',
      email: 'michael_andrew_simmons62@aol.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Taylor',
      surname: 'Bell',
      age: '63',
      email: 'taylorbell@live.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Melissa',
      surname: 'Lopez',
      age: '52',
      email: 'melissadawnlopez72@ymail.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Joshua',
      surname: 'Jenkins',
      age: '49',
      email: 'j_jenkins@ymail.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Rachel',
      surname: 'Johnson',
      age: '45',
      email: 'r_i_johnson@yahoo.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'David',
      surname: 'Murphy',
      age: '47',
      email: 'davidrmurphy@ymail.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Thomas',
      surname: 'Kelly',
      age: '44',
      email: 't.g.kelly@rocketmail.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Lauren',
      surname: 'Rodriguez',
      age: '44',
      email: 'lauren@ymail.com',
      education: 'Master’s degree',
    },
    {
      givenName: 'Daniel',
      surname: 'Brown',
      age: '53',
      email: 'daniel_brown@ymail.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Sebastian',
      surname: 'Diaz',
      age: '32',
      email: 's.j.diaz@live.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Julian',
      surname: 'Wood',
      age: '24',
      email: 'j.g9@rocketmail.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Benjamin',
      surname: 'James',
      age: '57',
      email: 'b_e_james71@live.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Taylor',
      surname: 'Henderson',
      age: '46',
      email: 'taylorhenderson@hotmail.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Austin',
      surname: 'Bennett',
      age: '52',
      email: 'abennett@ymail.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Nathan',
      surname: 'Peterson',
      age: '74',
      email: 'n_peterson23@yahoo.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Lauren',
      surname: 'Diaz',
      age: '44',
      email: 'l.m.diaz95@hotmail.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Sarah',
      surname: 'White',
      age: '55',
      email: 'sarah.faith.white@rocketmail.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Emily',
      surname: 'King',
      age: '60',
      email: 'emking@rocketmail.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Maria',
      surname: 'Long',
      age: '33',
      email: 'mflong@aol.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Kelsey',
      surname: 'Hall',
      age: '64',
      email: 'k.hall@gmail.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Isaac',
      surname: 'Smith',
      age: '68',
      email: 'i.a.smith@live.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Kelsey',
      surname: 'Bryant',
      age: '43',
      email: 'kelsey.m@live.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Jennifer',
      surname: 'Bennett',
      age: '32',
      email: 'jbennett@hotmail.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Victoria',
      surname: 'Russell',
      age: '18',
      email: 'victoria_russell42@aol.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Jason',
      surname: 'Reed',
      age: '51',
      email: 'jason15@ymail.com',
      education: 'Less than high school',
    },
    {
      givenName: 'David',
      surname: 'Washington',
      age: '35',
      email: 'davidwashington57@rocketmail.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Kelsey',
      surname: 'Williams',
      age: '67',
      email: 'k_e_williams40@rocketmail.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Joseph',
      surname: 'Kelly',
      age: '33',
      email: 'j.c.kelly@hotmail.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Sebastian',
      surname: 'Jenkins',
      age: '49',
      email: 'sebastianjenkins@rocketmail.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Richard',
      surname: 'Stewart',
      age: '21',
      email: 'r.stewart@aol.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Nicole',
      surname: 'Bell',
      age: '40',
      email: 'nicole.bell@rocketmail.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Ashley',
      surname: 'Taylor',
      age: '65',
      email: 'a_r_taylor@live.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Allison',
      surname: 'Cook',
      age: '47',
      email: 'a_cook@ymail.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Alyssa',
      surname: 'Phillips',
      age: '67',
      email: 'alyssa_phillips@outlook.com',
      education: 'Bachelor’s degree',
    },
    {
      givenName: 'Kayla',
      surname: 'Harris',
      age: '72',
      email: 'k.l.harris@rocketmail.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Maria',
      surname: 'Williams',
      age: '41',
      email: 'maria.mary.williams@live.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'William',
      surname: 'Ross',
      age: '56',
      email: 'wross@ymail.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Erin',
      surname: 'Bell',
      age: '73',
      email: 'erinlynn@hotmail.com',
      education: 'Master’s degree',
    },
    {
      givenName: 'Jennifer',
      surname: 'James',
      age: '28',
      email: 'jjames47@yahoo.com',
      education: 'High school diploma or equivalent',
    },
    {
      givenName: 'Audrey',
      surname: 'Adams',
      age: '33',
      email: 'a.adams@live.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Courtney',
      surname: 'Lee',
      age: '72',
      email: 'c_lee3@rocketmail.com',
      education: 'Less than high school',
    },
    {
      givenName: 'Victoria',
      surname: 'Stewart',
      age: '53',
      email: 'victoria.grace.stewart@gmail.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Allison',
      surname: 'Perry',
      age: '47',
      email: 'a.perry18@outlook.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Michael',
      surname: 'Hernandez',
      age: '66',
      email: 'michael_t@rocketmail.com',
      education: 'Associate degree',
    },
    {
      givenName: 'Matthew',
      surname: 'Thomas',
      age: '39',
      email: 'matthew.g@live.com',
      education: 'Some college, no degree',
    },
    {
      givenName: 'Isabella',
      surname: 'Howard',
      age: '65',
      email: 'isabella_renee_howard@outlook.com',
      education: 'Doctoral degree',
    },
    {
      givenName: 'Ryan',
      surname: 'Lopez',
      age: '58',
      email: 'ryanmlopez23@rocketmail.com',
      education: 'Associate degree',
    },
  ];